### ISSUE TITLE
`GM_xmlhttpRequest` for GM_* API casing

### ISSUE THREAD

**Issue by Martii** [Frederick888/pawoo-twitter-preview#1]
Seems like you have a casing typo here a few times:

``` diff
--- /scripts/Frederick888/Pawoo_Twitter_Preview/source@0.2.0+3007a08
+++ /scripts/Frederick888/Pawoo_Twitter_Preview/source
@@ -12,7 +12,7 @@
 // @updateURL       https://openuserjs.org/meta/Frederick888/Pawoo_Twitter_Preview.meta.js
 // @match           https://pawoo.net/*
 // @grant           GM.xmlHttpRequest
-// @grant           GM_xmlHttpRequest
+// @grant           GM_xmlhttpRequest
 // ==/UserScript==

 let galleryTemplate = `
@@ -34,10 +34,10 @@

 function fetchTwitterPreviewImage(twitterLink) {
     let twitterUrl = twitterLink.getAttribute('href');
-    if (typeof (GM_xmlHttpRequest) === 'undefined' && typeof (GM.xmlHttpRequest) === 'function') {
-        GM_xmlHttpRequest = GM.xmlHttpRequest;
+    if (typeof (GM_xmlhttpRequest) === 'undefined' && typeof (GM.xmlHttpRequest) === 'function') {
+        GM_xmlhttpRequest = GM.xmlHttpRequest;
     }
-    GM_xmlHttpRequest({
+    GM_xmlhttpRequest({
         method: 'GET',
         url: twitterUrl,
         headers: {
@@ -55,7 +55,7 @@
                 // console.log(openGraphImage.getAttribute('content'));
                 mediaGallery.querySelector('a.media-gallery__item-thumbnail').setAttribute('href', twitterUrl);
                 let container = twitterLink.closest('.status__content');
-                GM_xmlHttpRequest({
+                GM_xmlhttpRequest({
                     method: 'GET',
                     url: openGraphImage.getAttribute('content'),
                     headers: {

```

Refs:

* https://wiki.greasespot.net/GM.xmlHttpRequest
* https://sourceforge.net/p/greasemonkey/wiki/GM_xmlhttpRequest/
* https://www.tampermonkey.net/documentation.php#GM_xmlhttpRequest

See also https://openuserjs.org/scripts/Frederick888/Pawoo_Twitter_Preview/issues/%60GM_xmlhttpRequest%60_for_GM__API_casing . Apologies missed the `@supportURL` so mirrored here and closed over there. Non-OUJS-critical so I can do it here. :)

**Comment by Frederick888** [comment]
Thanks for spotting this issue! I've just applied your patch and released a new version.

I actually did quickly test it in Tampermonkey and it was working all right... Maybe they've already provided some sort of alias in the extension itself...?

**Comment by Martii** [comment]
Welcome. Thanks for supporting the original API. :) 

> Maybe they've already provided some sort of alias in the extension itself...?

Refs:
* https://github.com/Tampermonkey/tampermonkey/issues/579#issuecomment-406954289 . I think it's still a tender point point between GM and TM *(perhaps the entire community)* I think. Safari 13+ is hitting some bumps atm, See https://github.com/Tampermonkey/tampermonkey/issues/558 , so there may be some new contenders to the realm of .user.js to deal with. Synchronous vs. Asynchronous... the former is a little easier for most to understand but time will tell. From what I view as Admin on OUJS I see more of the GM_* than the GM.* API from a statistical point of view.
* https://github.com/violentmonkey/violentmonkey/issues/283 VM needs the polyfill *(or equivalent like yours)* currently *([mirrored on OUJS](https://openuserjs.org/libs/sizzle/gm4-polyfill))*
* https://openuserjs.org/announcements/Greasemonkey_Port_Update#comment-14fae44b994 Not sure on the status of SM as of today and running a bit behind in my normal duties there. I did however try it on a next build many, many, many, many, etc. months ago and it was still functional with the GM_* API. Still awaiting what's going to happen from Philip and the rest of the team. SM definitely needs the polyfill too atm.

> ... spotting this issue

Now that JSHint is configured a bit more in Ace on OUJS it showed me a warning triangle while viewing and I was like "Wha?? [Just fixed this](https://github.com/OpenUserJS/OpenUserJS.org/pull/1641)!" and then noticed the casing. :smile_cat:
